### ISSUE TITLE
Poor accuracy

### ISSUE THREAD

**Issue by bkanber** [mljs/random-forest#10]
Using your example with the Iris dataset I'm only getting around 75% accuracy. I believe a random forest should be able to fit the Iris dataset to around 90%. Do you get the same accuracy as me? I'm concerned because there might be an issue with the implementation of either the forest or the decision tree classifier.

**Comment by danielgwilson** [comment]
@bkanber I agree... here's [a pretty good Kaggle notebook](https://www.kaggle.com/aceccon/2-iris-dataset-basic-classification-algorithms) on the expected performance of several popular algorithms.

Also, [this Medium post](https://medium.com/@haydar_ai/learning-data-science-day-21-decision-tree-on-iris-dataset-267f3219a7fa) appears to demonstrate that a standard decision tree should perform much better—I also get ~74% accuracy.

I'm poking around, but it's unclear what's wrong with the implementation—or, perhaps the way both of us tested it (I used the example code).

```js
import IrisDataset from "ml-dataset-iris";
import { DecisionTreeClassifier as DTClassifier } from "ml-cart";
import { RandomForestClassifier as RFClassifier } from "ml-random-forest";

const trainingSet = IrisDataset.getNumbers();
const predictions: Array<number> = IrisDataset.getClasses().map(
    (elem: string) => IrisDataset.getDistinctClasses().indexOf(elem)
);

function getAccuracy(
    predictions: Array<number>,
    target: Array<number>
): number {
    const nSamples = predictions.length;
    let nCorrect = 0;
    predictions.forEach((val, idx) => {
        if (val == target[idx]) {
            nCorrect++;
        }
    });
    return nCorrect / nSamples;
}

// decision tree classifier
(() => {
    console.log("Decision Tree Model");
    const options = {
        gainFunction: "gini",
        maxDepth: 10,
        minNumSamples: 3
    };

    const classifier = new DTClassifier(options);
    classifier.train(trainingSet, predictions);
    const result = classifier.predict(trainingSet);

    console.log(`Accuracy: ${getAccuracy(result, predictions)}`); // Accuracy: 0.74
})();

// random forest classifier
(() => {
    console.log("Random Forest Model");
    const options = {
        seed: 3,
        maxFeatures: 0.8,
        replacement: true,
        nEstimators: 25
    };

    const classifier = new RFClassifier(options);
    classifier.train(trainingSet, predictions);
    const result = classifier.predict(trainingSet);

    console.log(`Accuracy: ${getAccuracy(result, predictions)}`); // Accuracy: 0.74
})();
```

**Comment by xdadda** [comment]
Guys this is a serious issue.
This level of accuracy seems to point to an implementation error.
How come no one has addressed this point yet, after more than a year?

**Comment by targos** [comment]
It has not been fixed because we (maintainers) didn't have time to look into it yet.
Contributions by anyone are welcome, so feel free to work on it and open a pull request.

**Comment by fabriond** [comment]
I've done some testing and I've detected what the problem might be, but I'm not sure how to fix it so I'm just going to post it here if anyone wants to check it out.

The problem seems to be on the ml-cart project, in the utils.js file and more specifically in the getNumberOfClasses function.

I've tested this using this lib (ml-random-forest) together with ml-cross-validation, ml-dataset-iris and ml-cart for comparison, the issue seems to be that the number of classes sometimes is wrongly detected, leading to a lot of NaNs throughout the execution and thus a large error rate.

The default accuracy rate seemed to be around 71.3% for ml-random-forest and around 72.6% for ml-cart.

After I changed the getNumberOfClasses function to return 3 by default (3 is the actual number of classes for the mt-dataset-iris dataset) the accuracy rate went up to 96% for ml-random-forest and 95.3% for ml-cart and there were no more NaN values being passed, so that seems to solve that problem.

What I'm not sure of is how to make it so the getNumberOfClasses function works correctly in general, not only on a case-by-case basis. A partial solution would be to add the ability to set the number of classes manually for the ml-cart implementation, thus making it one of the options in the object treeOptions in ml-random-forest.

**Comment by fabriond** [comment]
I've made a pull request on the [ml-cart repository](https://github.com/mljs/decision-tree-cart) with corrections related to my previous comment on this issue: https://github.com/mljs/decision-tree-cart/pull/10

**Comment by targos** [comment]
I released version 2.0.1 which includes the fix from https://github.com/mljs/decision-tree-cart/pull/10. Does it fix this issue?

**Comment by xdadda** [comment]
Just tested on the IRIS dataset as per danielgwilson post.
Accuracy jumped from 74% to 98%. 
Well done guys!! Will try with other datasets.

**Comment by aiday-mar** [comment]
accuracy increased to 98%, issue closed
